---
title: "Automated ingestion and conversion of various single-cell data formats"
author: "`r rworkflows::use_badges(branch='main')`" 
date: "<h4>Most recent update: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  github_document 
---

# Intro

There's a lot of single-cell omics file/object formats out there, and not all tools support all of these formats. `scKirby` aims to make switching between these formats much easier by running several steps within a single function: `ingest_data()`. Alternatively, users can run any of these steps separately using the designated sub-functions. 

1. **Read**: Automatically infers the file/object type and loads it (sub-function: `read_data()`).  
2. **Convert**: Converts it to the desired file/object type (sub-function: `to_<format>`). 
3. **Save**: Saves the converted file/object (sub-function: `save_data()`).


## [Documentation website](https://neurogenomics.github.io/scKirby)  
## [Vignette: data ingestion](https://neurogenomics.github.io/scKirby/articles/scKirby.html)  
## [Vignette: conda environments](https://neurogenomics.github.io/scKirby/articles/conda.html)  

# i/o formats 

## Supported input formats

- [SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html) 
- [SummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html)  
- [HDF5SummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/HDF5Array.html) 
- [Seurat](https://satijalab.org/seurat/index.html)  
- [H5Seurat](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html) 
- [anndata](https://github.com/rcannood/anndata) 
- [loom](http://loompy.org/) 
- [loomR](https://satijalab.org/loomR/loomR_tutorial.html) 
- [CellDataSet/monocle](http://cole-trapnell-lab.github.io/monocle-release/docs/#getting-started-with-monocle) 
- [ExpressionSet](https://www.rdocumentation.org/packages/Biobase/versions/2.32.0/topics/ExpressionSet)
- list
- [EWCE](https://github.com/NathanSkene/EWCE) 
- [matrix](https://cran.r-project.org/web/packages/Matrix/index.html)
- [sparseMatrix (dgTMatrix/dgCMatrix)](https://slowkow.com/notes/sparse-matrix/) 
- [DelayedArray](https://petehaitch.github.io/BioC2020_DelayedArray_workshop/articles/Effectively_using_the_DelayedArray_framework_for_users.html) 

## Supported output formats 

- [SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html)   
- [HDF5SummarizedExperiment](https://bioconductor.org/packages/release/bioc/html/HDF5Array.html)  
- [Seurat](https://satijalab.org/seurat/index.html)   
- [H5Seurat](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html)  
- [anndata](https://github.com/rcannood/anndata) 
- list

## Planned output formats 
 
- [loom](http://loompy.org/) 
- [CellDataSet/monocle](http://cole-trapnell-lab.github.io/monocle-release/docs/#getting-started-with-monocle) 

**Notes**: 

- For exporting to additional formats, see these following packages:  
  + [sceasy](https://github.com/cellgeni/sceasy)  
  + [zellkonverter](https://theislab.github.io/zellkonverter/articles/zellkonverter.html) 
  
- Currently, some (but not all) conversions carry over: 
  + Multiple assays per experiment. 
  + Additional objects like dimensionality reduction projections (e.g. PCA, tSNE, UMAP) or graphs (e.g. K-nearest neighbors). This feature will be added in the future.   


# Installation 

```R
if(!require("remotes")) install.packages("remotes")

remotes::install_github("neurogenomics/scKirby")
```

# Conda environments  

## Updating Seurat objects 

Seurat's `UpdateSeuratObject()` can only update objects from the version immediately previous to the version of Seurat you currently have installed (e.g. Seurat v2 --> v3). This means you can't import an object created in Seurat v1 and directly upgrade it to Seurat v3. We have provided yaml files when can be used to create separate envs for each version of Seurat [here](https://github.com/RajLabMSSM/echoconda/tree/main/inst/conda).  

For more details, see the [scKirby conda env tutorial](https://neurogenomics.github.io/scKirby/articles/conda.html). 
  
  
# Session Info

<details>

```{r Session Info}
utils::sessionInfo()
```

</details>
<hr>
